import hashlib

scam_patterns = [
    "bank verification",
    "unusual activity detected",
    "security alert",
    "overdue payment",
    "pending transaction",
    "wire transfer",
    "account compromise",
    "unauthorized login",
    "bank refund",
    "credit card declined",
    "you've won a prize",
    "congratulations, you've won",
    "claim your reward",
    "free gift",
    "lucky draw",
    "winning code",
    "unclaimed prize",
    "cash reward",
    "grand prize",
    "sweepstakes winner",
    "tax refund",
    "refund approval",
    "back taxes owed",
    "IRS payment required", 
    "government audit",
    "tax fraud warning",
    "revenue service alert",
    "tax debt settlement",
    "quick profit",
    "double your money",
    "guaranteed returns",
    "crypto investment",
    "binary options",
    "risk-free investment",
    "forex trading",
    "multi-level marketing",
    "investment opportunity",
    "real estate deal",
    "disaster relief donation",
    "support the cause",
    "urgent charity appeal",
    "charitable donation",
    "support our mission",
    "emergency aid fund",
    "fundraising appeal",
    "computer virus detected",
    "your device is infected",
    "urgent system alert",
    "unauthorized access detected",
    "windows support",
    "technical support team",
    "device hacked",
    "fix your system",
    "reset your password",
    "login to your account",
    "account update required",
    "confirm your identity",
    "verify your account",
    "password expired",
    "urgent action required",
    "email validation required",
    "click here to secure your account",
    "work from home",
    "urgent job offer",
    "high paying job",
    "easy money job",
    "guaranteed employment",
    "job application approved",
    "remote work opportunity",
    "earn from home",
    "immediate start job",
    "urgent help needed",
    "send money",
    "travel expenses",
    "can't meet in person",
    "love at first sight",
    "gift cards for love",
    "support me financially",
    "emergency funds",
    "free vacation",
    "travel offer",
    "luxury resort",
    "hotel confirmation",
    "cheap flights",
    "vacation package",
    "vacation giveaway",
    "time-share opportunity",
    "discounted hotel booking",
    "rental apartment available",
    "miracle cure",
    "weight loss guarantee",
    "cure for diabetes",
    "cancer treatment",
    "free medical consultation",
    "insurance claim",
    "health supplement",
    "COVID relief fund",
    "emergency medical bill",
    "court summons",
    "arrest warrant issued",
    "immediate legal action",
    "federal investigation",
    "unpaid fine",
    "law enforcement",
    "legal threat",
    "court order",
    "police case",
    "limited time offer",
    "exclusive deal",
    "super sale",
    "flash sale",
    "buy one get one free",
    "discount voucher",
    "order confirmation",
    "shopping spree",
    "pre-approved loan",
    "instant loan approval",
    "debt consolidation",
    "low interest rate loan",
    "easy repayment plan",
    "quick cash loan",
    "debt relief program",
    "bad credit loan",
    "electricity bill overdue",
    "gas payment overdue",
    "water supply cut-off",
    "utility payment required",
    "power outage alert",
    "disconnect notice",
    "immediate bill payment",
    "subscription renewal required",
    "Netflix subscription expired",
    "Amazon Prime renewal",
    "Spotify payment issue",
    "auto-renewal warning",
    "cancel subscription now",
    "Apple ID verification",
    "digital subscription service",
]

def hash_scam_patterns(patterns):
    return [hashlib.sha256(pattern.strip().lower().encode()).hexdigest() for pattern in patterns]

hashed_scam_patterns = hash_scam_patterns(scam_patterns)